### PR TITLE
StateFun workshop data simulator

### PR DESCRIPTION
**Pull request by sjwiesman**
The data simulator is used to generate JSON messages consumed by the workshop exercises. It is fully contained on a separate branch as a pre-built image will be made available to participants.

### CODE REVIEW

**Comment by alpinegizmo** [comment]
Looks good, just one thing. Could you maybe add a line or two to the README explaining how I work with this (since the pre-built image for workshop participants doesn't exist yet)?

**Comment by alpinegizmo** [comment]
I see now that you documented this in the other PR. I think we should capture that info in this README for future maintainers.

**Comment by sjwiesman** [comment]
Agreed, I'll update the README

**Comment by sjwiesman** [comment]
I screwed this up, I've reopened as #11

**Pull request merged**
